### ISSUE TITLE
Paragraphs are not needed

### ISSUE THREAD

**Issue by odv** [RazvanBugoi/Random-Colours-Game#1]
Please read the following:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

https://github.com/RazvanBugoi/Random-Colours-Game/blob/9ec3e05fb367eafe3219cfcea2ec25e865ae525f/index.html#L26

**Comment by RazvanBugoi** [comment]
Solved.
