### ISSUE TITLE
Replace textarea with heading

### ISSUE THREAD

**Issue by odv** [RazvanBugoi/Random-Colours-Game#2]
Populate it using the following documentation:
https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/innerText

https://github.com/RazvanBugoi/Random-Colours-Game/blob/9ec3e05fb367eafe3219cfcea2ec25e865ae525f/index.html#L15

**Comment by RazvanBugoi** [comment]
Solved.
