### ISSUE TITLE
Get your elements in one place by using a class name

### ISSUE THREAD

**Issue by odv** [RazvanBugoi/Random-Colours-Game#5]
Use the following documentation:
https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName

Parse your list of elements with a for loop.

https://github.com/RazvanBugoi/Random-Colours-Game/blob/9ec3e05fb367eafe3219cfcea2ec25e865ae525f/script.js#L4

**Comment by RazvanBugoi** [comment]
Solved.
